#
# Set up test Ubuntu box with Vagrant and VirtualBox:
#
#     vagrant up
#

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "precise64"
    config.vm.hostname = "hubotbox"
    config.vm.box_url = "http://files.vagrantup.com/precise64.box"

    config.vm.network :public_network

    # Build a virtual servers similar to production set up

    config.vm.define :hubotbox, primary: true do |hubotbox|
        hubotbox.vm.provision "ansible" do |ansible|
            ansible.playbook = "playbook.yml"
        end
    end
end
